language: node_js
node_js:
  - "10"
dist: trusty
sudo: false

branches:
  only:
  - master

cache:
  directories:
    - node_modules

install:
  - npm ci

script:
  - npm run build
  - npm run export
  - mv ./out/404/index.html ./out/404.html
  - node ./sitemap.js

deploy:
  provider: pages
  repo: observable-playground/observable-playground.github.io
  target_branch: master
  keep_history: true
  allow_empty_commit: true
  verbose: true
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: out
  on:
    branch: master